### ISSUE TITLE
Agent: Execute Command

### ISSUE THREAD

**Issue by DamSimm** [DamSimm/thin-dr#10]
Build method to take in command and execute on host, whether that command be an actual system command (`whoami`) or an agent command (`contain-host`).

**Comment by DamSimm** [comment]
We can execute basic Windows commands, don't try running `powershell` 😀

**Comment by Spar0w** [comment]
Added character escaping in [https://github.com/DamSimm/thin-dr/commit/c12af8d4398cc0214e7cf5f2f05686e01d9ce0f6](url). This makes sending data back to the server possible in cases like `whoami`
