### ISSUE TITLE
C2 Agent: Close Connections

### ISSUE THREAD

**Issue by samuel-barrows** [DamSimm/thin-dr#9]
A bug that I've noticed is that the client hangs up if  it's trying to query the server during the same server lifespan. The client doesn't seem to close connections, but it also may be an issue with the Server. @DamSimm if you could investigate further that would be awesome. It may be an issue with my Mac

**Comment by DamSimm** [comment]
@samuel-barrows was this server issue?

**Comment by samuel-barrows** [comment]
I haven't fully tested this yet but will if the issue persists. I believe it to be a server issue though

**Comment by DamSimm** [comment]
Tested locally with no issue.
